[package]
edition = "2021"
name = "daemon-slayer-plugin-task-queue"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aide-de-camp = {git = "https://github.com/aschey/aide-de-camp", rev = "628de0c0d78725c26bac493d50e27da595819ddf"}
aide-de-camp-sqlite = {git = "https://github.com/aschey/aide-de-camp", rev = "628de0c0d78725c26bac493d50e27da595819ddf", default-features = false, features = ["rustls"]}
async-trait = "0.1"
daemon-slayer-core = {path = "../../daemon-slayer-core", features = ["server"]}
log = "0.4"
tokio = {version = "1", features = ["sync"]}
tokio-stream = {version = "0.1", features = ["sync"]}
tracing = "0.1"
