[package]
edition = "2024"
name = "daemon-slayer-macros"
version = "0.1.0"
[lib]
proc-macro = true

[dependencies]
proc-macro-crate = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[features]
config = []
server = []
