[package]
edition = "2021"
name = "daemon-slayer-server"
version = "0.1.0"

[features]
async-tokio = ["tokio", "signal-hook-tokio", "async-trait", "futures", "daemon-slayer-macros/async"]
blocking = ["daemon-slayer-macros/blocking"]
direct = ["signal-hook", "daemon-slayer-macros/direct"]
ipc-health-check = ["parity-tokio-ipc", "async-tokio"]

[dependencies]
async-trait = {version = "0.1.57", optional = true}
daemon-slayer-macros = {path = "../daemon-slayer-macros", default-features = false}
futures = {version = "0.3.23", optional = true}
maybe-async-cfg = "0.2.3"
once_cell = "1.14.0"
parity-tokio-ipc = {version = "0.9.0", optional = true}
tracing = "0.1.36"

[target.'cfg(windows)'.dependencies]
signal-hook = {version = "0.3.14", optional = true}
tokio = {version = "1.20.1", features = ["rt-multi-thread", "signal", "net"], optional = true}
windows-service = {git = "https://github.com/aschey/windows-service-rs", rev = "467408c9aba7d8221e5cf5a9992765ad7abeeb55"}

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3.14"
signal-hook-tokio = {version = "0.3.1", features = ["futures-v0_3"], optional = true}
tokio = {version = "1.20.1", features = ["rt-multi-thread", "net", "io-util", "sync"], optional = true}

[target.'cfg(target_os="linux")'.dependencies]
sd-notify = "0.4.0"

[target.'cfg(target_os = "macos")'.dependencies]
launchd = "0.2.0"

[dev-dependencies]
assert_cmd = "2.0.4"
