[package]
edition = "2021"
name = "socket-activated"
version = "0.1.0"

[dependencies]
axum = "0.8.1"
confique = "0.3.0"
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
  "client-standard",
  "server-standard",
  "tray",
  "build-info",
  "socket-activation",
] }
daemon-slayer-logging = { path = "../../crates/daemon-slayer-logging", features = [
  "system",
  "ipc",
] }
derive_more = { version = "1.0.0", default-features = false, features = [
  "as_ref",
] }
serde = "1.0.217"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["trace"] }
tracing = "0.1.41"

[[bin]]
name = "socket-activated-client"
path = "src/bin/client.rs"

[[bin]]
name = "socket-activated-server"
path = "src/bin/server.rs"

[build-dependencies]
vergen-gix = { version = "1.0", features = ["build", "cargo", "rustc", "si"] }
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
  "build-info",
] }
