[package]
edition = "2021"
name = "socket-activated"
version = "0.1.0"

[dependencies]
axum = "0.6.20"
confique = "0.2.4"
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
    "client-standard",
    "server-standard",
    "tray",
    "build-info",
] }
daemon-slayer-logging = { path = "../../crates/daemon-slayer-logging", features = [
    "system",
    "ipc",
] }
derive_more = { version = "0.99.17", default-features = false, features = [
    "as_ref",
] }
serde = "1.0.180"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.4.3", features = ["trace"] }
tracing = "0.1.37"

[[bin]]
name = "socket-activated-client"
path = "src/bin/client.rs"

[[bin]]
name = "socket-activated-server"
path = "src/bin/server.rs"

[build-dependencies]
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
    "build-info",
    "build-info-build",
    "build-info-cargo",
    "build-info-git",
    "build-info-rustc",
    "build-info-si",
] }
