[package]
edition = "2024"
name = "socket-activated"
version = "0.1.0"

[dependencies]
axum = { workspace = true }
confique = { workspace = true }
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
  "client-standard",
  "server-standard",
  "tray",
  "build-info",
  "socket-activation",
  "logging-system",
  "logging-ipc",
] }
derive_more = { workspace = true, default-features = false, features = [
  "as_ref",
] }
serde = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower-http = { workspace = true, features = ["trace"] }
tracing = { workspace = true }

[[bin]]
name = "socket-activated-client"
path = "src/bin/client.rs"

[[bin]]
name = "socket-activated-server"
path = "src/bin/server.rs"

[build-dependencies]
vergen-gix = { workspace = true, features = ["build", "cargo", "rustc", "si"] }
daemon-slayer = { workspace = true, features = ["build-info"] }
