[package]
edition = "2021"
name = "socket-activated"
version = "0.1.0"

[dependencies]
axum = "0.7.5"
confique = "0.2.5"
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
    "client-standard",
    "server-standard",
    "tray",
    "build-info",
    "socket-activation",
] }
daemon-slayer-logging = { path = "../../crates/daemon-slayer-logging", features = [
    "system",
    "ipc",
] }
derive_more = { version = "1.0.0", default-features = false, features = [
    "as_ref",
] }
serde = "1.0.204"
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.5.2", features = ["trace"] }
tracing = "0.1.40"

[[bin]]
name = "socket-activated-client"
path = "src/bin/client.rs"

[[bin]]
name = "socket-activated-server"
path = "src/bin/server.rs"

[build-dependencies]
vergen-gix = { version = "1.0", features = ["build", "cargo", "rustc", "si"] }
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
    "build-info",
] }
