[package]
edition = "2021"
name = "daemon-slayer"
version = "0.1.0"

[workspace]
members = [
  "daemon-slayer-macros",
  "daemon-slayer-client",
  "daemon-slayer-server",
  "daemon-slayer-cli",
  "daemon-slayer-logging",
  "daemon-slayer-console",
  "integration-tests",
  "examples",
  "examples/src/grpc-tonic",
  "examples/src/http-axum",
]
resolver = "2"

[features]
all-async = ["async-client", "async-server", "daemon-slayer-cli/all-async"]
all-sync = ["sync-client", "sync-server", "daemon-slayer-cli/all-sync"]
async-client = ["console", "async-tokio", "client", "cli", "daemon-slayer-cli/async-client", "daemon-slayer-client/async-tokio"]
async-server = ["direct", "async-tokio", "server", "cli", "logging", "daemon-slayer-cli/async-server"]
async-tokio = [
  "daemon-slayer-server/async-tokio",
  "daemon-slayer-cli/async-tokio",
  "daemon-slayer-logging/async-tokio",
]
cli = ["daemon-slayer-cli"]
client = ["daemon-slayer-client"]
console = ["daemon-slayer-console", "daemon-slayer-cli/console"]
direct = ["daemon-slayer-server/direct", "daemon-slayer-cli/direct"]
grpc-health-check = ["daemon-slayer-client/grpc-health-check"]
http-health-check = ["daemon-slayer-client/http-health-check"]
ipc-health-check = ["daemon-slayer-client/ipc-health-check", "daemon-slayer-server/ipc-health-check"]
logging = ["daemon-slayer-logging"]
server = ["daemon-slayer-server"]
sync-client = ["client", "cli", "daemon-slayer-cli/sync-client", "daemon-slayer-client/blocking"]
sync-server = ["direct", "server", "logging", "cli", "daemon-slayer-cli/sync-server", "daemon-slayer-server/blocking"]

[dependencies]
daemon-slayer-cli = {path = "./daemon-slayer-cli", optional = true}
daemon-slayer-client = {path = "./daemon-slayer-client", optional = true}
daemon-slayer-console = {path = "./daemon-slayer-console", optional = true}
daemon-slayer-logging = {path = "./daemon-slayer-logging", optional = true}
daemon-slayer-server = {path = "./daemon-slayer-server", optional = true}
