[config]
default_to_workspace = false

[tasks.test]
args = ["hack", "--feature-powerset", "test", "--", "--nocapture"]
clear = true
command = "cargo"
install_crate = "cargo-hack"

[tasks.clippy]
args = ["hack", "--feature-powerset", "--no-dev-deps", "clippy", "--", "-D", "warnings"]
command = "cargo"
install_crate = "cargo-hack"

[tasks.build-all]
args = ["hack", "--feature-powerset", "--no-dev-deps", "build"]
command = "cargo"
install_crate = "cargo-hack"
