[config]
default_to_workspace = false

[tasks.test-admin]
args = ["test", "--workspace"]
clear = true
command = "cargo"
env = {RUN_AS_SYSTEM = "true"}

[tasks.test]
args = ["test", "--workspace"]
clear = true
command = "cargo"

[tasks.clippy]
args = ["hack", "--feature-powerset", "--no-dev-deps", "clippy", "--", "-D", "warnings"]
command = "cargo"
install_crate = "cargo-hack"

[tasks.build-all]
script = '''
cargo build --workspace
cargo build --workspace --features=client-standard,server-standard,grpc-health-check,http-health-check,ipc-health-check,extras,tray
'''

[tasks.build-examples]
script = '''
cd examples
cargo build --examples
cd examples/http-axum
cargo build
cd ../grpc-tonic
cargo build
'''

[tasks.build-coverage]
args = ["build", "--workspace"]
command = "cargo"
env = {RUSTFLAGS = "-Cinstrument-coverage", LLVM_PROFILE_FILE = "daemon-slayer-%p-%m.profraw"}

[tasks.gen-coverage]
args = ["test", "--workspace"]
command = "cargo"
dependencies = ["build-coverage"]
env = {RUSTFLAGS = "-Cinstrument-coverage", LLVM_PROFILE_FILE = "daemon-slayer-%p-%m.profraw"}

[tasks.copy-coverage]
dependencies = ["gen-coverage"]
script = '''
cp C:\Windows\System32\default.profraw .
'''

[tasks.gen-coverage-report]
args = [
  ".",
  "-s",
  ".",
  "--binary-path",
  "./target/debug/",
  "-t",
  "html",
  "--branch",
  "--ignore-not-existing",
  "--ignore",
  "target/**/*",
  "--ignore",
  "integration-tests/**/*",
  "--ignore",
  "daemon-slayer-macros/**/*",
  "-o",
  "./target/debug/coverage/",
]
command = "grcov"
dependencies = ["copy-coverage"]
install_crate = {rustup_component_name = "llvm-tools-preview", crate_name = "grcov"}

[tasks.cleanup-coverage]
clear = true
dependencies = ["gen-coverage-report"]
script = """
rm *.profraw
handle = glob_array ./**/*.profraw
for path in ${handle}
    rm ${path}
end
"""
script_runner = "@duckscript"

[tasks.coverage]
clear = true
dependencies = ["cleanup-coverage"]
script = "xdg-open target/debug/coverage/index.html"

[tasks.coverage.windows]
clear = true
dependencies = ["cleanup-coverage"]
script = "./target/debug/coverage/index.html"
script_runner = "@shell"
