[config]
default_to_workspace = false

[tasks.test]
args = ["hack", "--feature-powerset", "test", "--", "--nocapture"]
clear = true
command = "cargo"
install_crate = "cargo-hack"

[tasks.clippy]
args = ["hack", "--feature-powerset", "--no-dev-deps", "clippy", "--", "-D", "warnings"]
command = "cargo"
install_crate = "cargo-hack"

[tasks.build-extra]
script = '''
cargo build --features=ipc-health-check,http-health-check --examples
cargo build --features=all-async,ipc-health-check,http-health-check --examples
cargo build --features=all-sync,ipc-health-check,http-health-check --examples
cargo build --features=all-async,all-sync,ipc-health-check,http-health-check --examples
'''

[tasks.build-all]
args = [
  "hack",
  "--feature-powerset",
  "--exclude-features",
  "cli client server console direct logging server async-tokio ipc-health-check http-health-check",
  "build",
  "--examples",
]
command = "cargo"
dependencies = ["build-extra"]
install_crate = "cargo-hack"
