[config]
default_to_workspace = false

[tasks.test]
args = ["hack", "--feature-powerset", "test", "--", "--nocapture"]
clear = true
command = "cargo"
install_crate = "cargo-hack"

[tasks.clippy]
args = ["hack", "--feature-powerset", "--no-dev-deps", "clippy", "--", "-D", "warnings"]
command = "cargo"
install_crate = "cargo-hack"

[tasks.build-all]
args = [
  "hack",
  "--feature-powerset",
  "--exclude-features",
  "cli client server console direct logging server async-tokio",
  "build",
  "--examples",
]
command = "cargo"
install_crate = "cargo-hack"

[tasks.examples]
script = '''
cargo build --example=async_client --features=async-client
cargo build --example=async_combined --features=all
cargo build --example=async_server --features=async-server
cargo build --example=sync_client --features=sync-client
cargo build --example=sync_combined --features=all-sync
cargo build --example=sync_server --features=sync-server
cargo build --example=axum --features=all
'''
