[package]
edition = "2021"
name = "daemon-slayer-console"
version = "0.1.0"

[dependencies]
confique = { version = ">= 0.2.2", optional = true }
crossterm = { version = "0.26", features = ["event-stream"] }
daemon-slayer-client = { path = "../daemon-slayer-client" }
daemon-slayer-core = { path = "../daemon-slayer-core", features = [
    "server",
    "config",
    "health-check",
], optional = true }
futures = { version = "0.3" }
serde = { version = "1", optional = true }
tilia-widget = { git = "https://github.com/aschey/tilia", rev = "a1db1e87be38712cf9a20db7ea06f27278185e9a", features = [
    "ipc",
    "docker",
] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
ratatui = { version = "0.21" }
tower-rpc = { git = "https://github.com/aschey/tower-rpc", rev = "7cc9de34f32e9cb5d6bc9e22ba0508011fd7d580", features = [
    "client",
    "server",
    "ipc",
] }


[features]
cli = ["daemon-slayer-core/cli"]
config = ["confique", "serde"]
