[package]
edition = "2021"
name = "daemon-slayer-console"
version = "0.1.0"

[dependencies]
confique = {version = ">= 0.2.2", optional = true}
crossterm = {version = "0.25", features = ["event-stream"]}
daemon-slayer-client = {path = "../daemon-slayer-client"}
daemon-slayer-core = {path = "../daemon-slayer-core", features = ["server", "config", "health-check"], optional = true}
futures = {version = "0.3"}
serde = {version = "1", optional = true}
tilia-widget = {git = "https://github.com/aschey/tilia", rev = "f62f771e44cb043b57e430bc1e113dbc543ad939"}
tokio = {version = "1", features = ["rt-multi-thread", "macros"]}
tui = {version = "0.19"}

[features]
cli = ["daemon-slayer-core/cli"]
config = ["confique", "serde"]
