[package]
edition = "2021"
name = "daemon-slayer-console"
version = "0.1.0"

[dependencies]
confique = { version = ">= 0.2.2", optional = true }
crossterm = { version = "0.27", features = ["event-stream"] }
daemon-slayer-client = { path = "../daemon-slayer-client" }
daemon-slayer-core = { path = "../daemon-slayer-core", features = [
    "server",
    "config",
    "health-check",
], optional = true }
futures = { version = "0.3" }
serde = { version = "1", optional = true }
tilia-widget = { git = "https://github.com/aschey/tilia", rev = "1bbb4151b8f16df98775dc2c4367b2da884dce47", features = [
    "ipc",
    "docker",
] }
tilia = { git = "https://github.com/aschey/tilia", rev = "1bbb4151b8f16df98775dc2c4367b2da884dce47", features = [
    "ipc",
    "docker",
] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
ratatui = { version = "0.23" }


[features]
cli = ["daemon-slayer-core/cli"]
config = ["confique", "serde"]
