[package]
edition = "2024"
name = "minimal-combined"
version = "0.1.0"

[dependencies]
clap = { workspace = true, features = ["derive"] }
daemon-slayer = { workspace = true, features = ["client", "server", "signals"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
