[package]
edition = "2024"
name = "daemon-slayer-process"
version = "0.1.0"

[dependencies]
bytesize = { workspace = true, features = ["serde"] }
chrono = { workspace = true, features = ["serde"] }
daemon-slayer-core = { workspace = true }
num_cpus = { workspace = true }
readonly = { workspace = true }
serde = { workspace = true }
strum = { workspace = true, features = ["derive"] }
sysinfo = { workspace = true }
async-trait = { workspace = true, optional = true }

[features]
cli = ["daemon-slayer-core/cli", "async-trait"]
