[package]
edition = "2021"
name = "daemon-slayer-cli"
version = "0.1.0"

[features]
async-tokio = ["tokio", "async-trait", "futures", "maybe-async/is_async"]
client = ["daemon-slayer-client"]
console = ["daemon-slayer-console", "async-tokio"]
default = ["client", "server"]
direct = []
server = ["daemon-slayer-server"]

[dependencies]
async-trait = {version = "0.1.57", optional = true}
clap = {version = "3.2.17", features = ["cargo"]}
daemon-slayer-client = {path = "../daemon-slayer-client", optional = true}
daemon-slayer-console = {path = "../daemon-slayer-console", optional = true}
daemon-slayer-logging = {path = "../daemon-slayer-logging", optional = true}
daemon-slayer-server = {path = "../daemon-slayer-server", optional = true}
eyre = "0.6.8"
futures = {version = "0.3.23", optional = true}
maybe-async = {git = "https://github.com/aschey/maybe-async-rs", rev = "36bb795e18e88aa0642164934d50d8c5ee05e26f", features = ["default_sync"]}
parity-tokio-ipc = "0.9.0"
time = {version = "0.3.13", optional = true}
tokio = {version = "1.20.1", features = ["rt-multi-thread", "macros"], optional = true}
tracing = "0.1.36"
