[package]
edition = "2021"
name = "daemon-slayer-cli"
version = "0.1.0"

[dependencies]
async-trait = {version = "0.1", optional = true}
clap = {version = "4", features = ["string"]}
daemon-slayer-core = {path = "../daemon-slayer-core"}
tracing = "0.1"
