[package]
edition = "2021"
name = "standard"
version = "0.1.0"

[dependencies]
confique = "0.2.4"
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
    "client-standard",
    "server-standard",
    "tray",
    "build-info",
] }
daemon-slayer-logging = { path = "../../crates/daemon-slayer-logging", features = [
    "system",
    "ipc",
] }
derive_more = { version = "0.99.17", default-features = false, features = [
    "as_ref",
] }
serde = "1.0.192"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"

[[bin]]
name = "standard-client"
path = "src/bin/client.rs"

[[bin]]
name = "standard-server"
path = "src/bin/server.rs"

[build-dependencies]
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
    "build-info",
    "build-info-build",
    "build-info-cargo",
    "build-info-git",
    "build-info-rustc",
    "build-info-si",
] }
