[package]
edition = "2021"
name = "standard"
version = "0.1.0"

[dependencies]
confique = "0.2.2"
daemon-slayer = {path = "../../crates/daemon-slayer", features = ["client-standard", "server-standard"]}
serde = "1.0.151"
tokio = {version = "1.23.0", features = ["macros", "rt-multi-thread"]}
tracing = "0.1.37"

[[bin]]
name = "standard-client"
path = "src/bin/client.rs"

[[bin]]
name = "standard-server"
path = "src/bin/server.rs"
