[package]
edition = "2024"
name = "standard"
version = "0.1.0"

[dependencies]
confique = { workspace = true }
daemon-slayer = { workspace = true, features = [
  "client-standard",
  "server-standard",
  "tray",
  "build-info",
  "logging-system",
  "logging-ipc",
] }
derive_more = { workspace = true, default-features = false, features = [
  "as_ref",
] }
serde = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }

[[bin]]
name = "standard-client"
path = "src/bin/client.rs"

[[bin]]
name = "standard-server"
path = "src/bin/server.rs"

[build-dependencies]
vergen-gix = { workspace = true, features = ["build", "cargo", "rustc", "si"] }
