[package]
edition = "2024"
name = "daemon-slayer-tray"
version = "0.1.0"

[dependencies]
daemon-slayer-client = { path = "../daemon-slayer-client" }
image = "0.25"
tao = "0.33"
tokio = { version = "1", features = ["sync", "macros", "time"] }
tray-icon = { git = "https://github.com/aschey/tray-icon", rev = "7f72639d241164babc10185695d5db2ec8420b4f" }
