[package]
edition = "2021"
name = "daemon-slayer-tray"
version = "0.1.0"

[dependencies]
daemon-slayer-client = { path = "../daemon-slayer-client" }
image = "0.25"
tao = "0.27"
tokio = { version = "1", features = ["sync", "macros", "time"] }
tray-icon = "0.13"
