[package]
edition = "2024"
name = "daemon-slayer-tray"
version = "0.1.0"

[dependencies]
daemon-slayer-client = { workspace = true }
image = { workspace = true }
tao = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros", "time"] }
tray-icon = { workspace = true }
