[package]
edition = "2024"
name = "daemon-slayer-signals"
version = "0.1.0"

[dependencies]
daemon-slayer-core = { workspace = true, features = ["server", "signal"] }
futures = { workspace = true }
tracing = { workspace = true }
tap = { workspace = true }

[target.'cfg(unix)'.dependencies]
signal-hook = { workspace = true }
signal-hook-tokio = { workspace = true, features = ["futures-v0_3"] }
tokio = { workspace = true, features = [
  "rt-multi-thread",
  "net",
  "io-util",
  "sync",
  "macros",
] }

[target.'cfg(windows)'.dependencies]
signal-hook = { workspace = true }
tokio = { workspace = true, features = [
  "rt-multi-thread",
  "net",
  "io-util",
  "sync",
  "macros",
  "signal",
] }
