[package]
edition = "2021"
name = "custom-command"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
    "client-standard",
    "server-standard",
] }
derive_more = { version = "0.99.17", default-features = false, features = [
    "as_ref",
] }
serde = "1.0.197"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
