
[workspace]
exclude = ["old", "target", "assets"]
members = ["*"]
resolver = "3"

[workspace.dependencies]
confique = "0.4.0"
daemon-slayer = { path = "../crates/daemon-slayer" }
derive_more = { version = "2.1.1", default-features = false }
serde = "1.0.229"
tar = "0.4.46"
tokio = { version = "1.53.1" }
tokio-util = { version = "0.7.19" }
tracing = "0.1.44"
bollard = { version = "0.21.1" }
flate2 = "1.1.10"
ignore = "0.4.33"
clap = { version = "4.6.6" }
http-body-util = "0.1.5"
tower-http = "0.7.0"
vergen-gix = "10.0.3"
axum = "0.8.9"
