[package]
authors = ["you"]
description = "A Tauri App"
edition = "2021"
license = ""
name = "daemon-slayer-gui"
repository = ""
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.1", features = [] }

[dependencies]
daemon-slayer-client = { path = "../../daemon-slayer-client" }
daemon-slayer-health-check = { path = "../../daemon-slayer-health-check", features = [
    "http-health-check",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "1.1", features = ["api-all", "system-tray"] }
tauri-plugin-positioner = { git = "https://github.com/aschey/tauri-plugin-positioner", features = [
    "system-tray",
] }
tilia = { git = "https://github.com/aschey/tilia", rev = "a1db1e87be38712cf9a20db7ea06f27278185e9a" }
tokio = { version = "1.21.2", features = ["time"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
