[package]
edition = "2024"
name = "notifications"
version = "0.1.0"

[dependencies]
confique = { workspace = true }
daemon-slayer = { workspace = true, features = [
  "client-standard",
  "server-standard",
  "native-notification",
  "dialog",
  "logging-system",
  "logging-ipc",
] }

derive_more = { workspace = true, default-features = false, features = [
  "as_ref",
] }
serde = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }

[[bin]]
name = "notification-client"
path = "src/bin/client.rs"

[[bin]]
name = "notification-server"
path = "src/bin/server.rs"
