[package]
edition = "2021"
name = "notifications"
version = "0.1.0"

[dependencies]
confique = "0.3.0"
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
  "client-standard",
  "server-standard",
  "native-notification",
  "dialog",
] }
daemon-slayer-logging = { path = "../../crates/daemon-slayer-logging", features = [
  "system",
  "ipc",
] }

derive_more = { version = "1.0.0", default-features = false, features = [
  "as_ref",
] }
serde = "1.0.217"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"

[[bin]]
name = "notification-client"
path = "src/bin/client.rs"

[[bin]]
name = "notification-server"
path = "src/bin/server.rs"
