[package]
edition = "2021"
name = "notifications"
version = "0.1.0"

[dependencies]
confique = "0.2.2"
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
    "client-standard",
    "server-standard",
    "notify",
] }
daemon-slayer-logging = { path = "../../crates/daemon-slayer-logging", features = [
    "system",
    "ipc",
] }

derive_more = { version = "0.99.17", default-features = false, features = [
    "as_ref",
] }
serde = "1.0.151"
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"

[[bin]]
name = "notification-client"
path = "src/bin/client.rs"

[[bin]]
name = "notification-server"
path = "src/bin/server.rs"
