[package]
edition = "2021"
name = "custom-signal-handler-async"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
ctrlc = "3.2.3"
daemon-slayer = {path = "../../..", features = ["client", "server", "cli", "console", "direct", "logging"]}
daemon-slayer-cli = {path = "../../../daemon-slayer-cli", features = ["all-async"]}
futures = "0.3.24"
tokio = {version = "1.20.1", features = ["rt-multi-thread", "time", "macros"]}
tracing = "0.1.36"
