[package]
edition = "2021"
name = "daemon-slayer-error-handler"
version = "0.1.0"

[features]
cli = ["daemon-slayer-core/cli"]

[dependencies]
color-eyre = "0.6"
daemon-slayer-core = {path = "../daemon-slayer-core"}
once_cell = "1"
tap = "1"
thiserror = "1"
tracing = "0.1"
