[package]
edition = "2021"
name = "daemon-slayer-plugin-ipc-health-check"
version = "0.1.0"

[dependencies]
async-trait = "0.1.57"
daemon-slayer-core = {path = "../../daemon-slayer-core"}
futures = "0.3"
parity-tokio-ipc = {version = "0.9"}
tokio = {version = "1", features = ["rt-multi-thread", "net", "io-util", "sync", "macros"]}
tracing = "0.1.37"
