[package]
edition = "2021"
name = "custom-signal-handler-sync"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.3"
daemon-slayer = {path = "../../..", features = ["direct", "server", "client", "cli", "logging"]}
daemon-slayer-cli = {path = "../../../daemon-slayer-cli", features = ["all-sync"]}
tracing = "0.1.36"
