[package]
name = "daemon-slayer-notify"
edition = "2024"
version = "0.1.0"

[dependencies]
daemon-slayer-core = { workspace = true, features = [
  "server",
  "notify",
  "process",
] }
tokio = { workspace = true, features = ["time"] }
tracing = { workspace = true }
notify-rust = { workspace = true, optional = true, features = ["async"] }
native-dialog = { workspace = true, features = [
  "windows_dpi_awareness",
  "windows_visual_styles",
], optional = true }
tap = { workspace = true }
async-trait = { workspace = true }

[features]
cli = ["daemon-slayer-core/cli"]
native-notification = ["notify-rust"]
dialog = ["native-dialog"]
