[package]
name = "daemon-slayer-notify"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daemon-slayer-core = { path = "../daemon-slayer-core", features = [
  "server",
  "notify",
  "process",
] }
tokio = { version = "1", features = ["time"] }
tracing = "0.1"
notify-rust = { version = "4", optional = true, features = ["async"] }
native-dialog = { version = "0.7", features = [
  "windows_dpi_awareness",
  "windows_visual_styles",
], optional = true }
tap = "1"
async-trait = "0.1"

[features]
cli = ["daemon-slayer-core/cli"]
native-notification = ["notify-rust"]
dialog = ["native-dialog"]
