[package]
edition = "2021"
name = "testapp"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daemon-slayer = {path = "../daemon-slayer"}
tokio = {version = "1.20.1", features = ["rt-multi-thread", "macros", "sync"]}
