[package]
edition = "2021"
name = "http-axum"
version = "0.1.0"

[workspace]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
async-trait = "0.1.57"
axum = "0.6.0-rc.2"
daemon-slayer = {path = "../../..", features = ["all-async", "http-health-check", "plugin-task-queue", "plugin-file-watcher", "plugin-ipc-health-check"]}
futures = "0.3.24"
reqwest = "0.11.11"
tokio = {version = "1.21.0", features = ["macros", "rt-multi-thread"]}
tower-http = {version = "0.3.4", features = ["trace"]}
tracing = "0.1.36"
