#!/usr/bin/env sh
source $(dirname $0)/.env

rsync -arv -e "sshpass -p ${QUICKEMU_MAC_PASSWORD} ssh -p 22221" --progress --delete --exclude target --exclude .git "${QUICKEMU_MAC_USERNAME}@localhost:/Users/${QUICKEMU_MAC_USERNAME}/daemon-slayer/" .