#!/usr/bin/env sh
source $(dirname $0)/.env

sshpass -p "${QUICKEMU_WINDOWS_PASSWORD}" ssh -p 22220 Quickemu@localhost << EOF
if not exist "C:\Users\Quickemu\daemon-slayer" (
    mkdir "C:\Users\Quickemu\daemon-slayer"
)
EOF
echo
rsync -arv -e "sshpass -p ${QUICKEMU_WINDOWS_PASSWORD} ssh -p 22220" --delete --progress --exclude target --exclude .git ./ Quickemu@localhost:/c/Users/Quickemu/daemon-slayer