#!/usr/bin/env sh
source $(dirname $0)/.env

rsync -arv -e "sshpass -p ${QUICKEMU_WINDOWS_PASSWORD} ssh -p 22220" --progress --delete --exclude target --exclude .git Quickemu@localhost:/c/Users/Quickemu/daemon-slayer/ .