#!/usr/bin/env sh
source $(dirname $0)/.env

sshpass -p "${QUICKEMU_MAC_PASSWORD}" ssh -p 22221 "${QUICKEMU_MAC_USERNAME}@localhost" << EOF
mkdir -p ~/daemon-slayer
EOF
echo
rsync -arv -e "sshpass -p ${QUICKEMU_MAC_PASSWORD} ssh -p 22221" --delete --progress --exclude target --exclude .git ./ "${QUICKEMU_MAC_USERNAME}@localhost:/Users/${QUICKEMU_MAC_USERNAME}/daemon-slayer"