#!/usr/bin/env sh
source $(dirname $0)/.env

$(dirname $0)/rsync-to-mac
sshpass -p "${QUICKEMU_MAC_PASSWORD}" ssh -p 22221 "${QUICKEMU_MAC_USERNAME}@localhost" << EOF
cd ~/daemon-slayer
cargo build
cargo test
EOF