[package]
edition = "2021"
name = "daemon-slayer-server"
version = "0.1.0"

[dependencies]
daemon-slayer-core = { path = "../daemon-slayer-core", features = [
    "server",
    "signal",
] }
daemon-slayer-macros = { path = "../daemon-slayer-macros", features = [
    "server",
] }
futures = { version = "0.3" }
tap = "1"
thiserror = "1"
tracing = "0.1"
tipsy = { version = "0.2", optional = true }
async-trait = { version = "0.1", optional = true }

[target.'cfg(windows)'.dependencies]
registry = "1"
signal-hook = { version = "0.3", optional = true }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "signal",
    "net",
    "macros",
    "sync",
] }
windows-service = { git = "https://github.com/aschey/windows-service-rs", rev = "32919aebe4c59f7855a8ebd72fe7d716db6a8f28" }


[target.'cfg(unix)'.dependencies]
tokio = { version = "1", features = [
    "rt-multi-thread",
    "net",
    "io-util",
    "sync",
    "macros",
] }

[target.'cfg(target_os="linux")'.dependencies]
sd-notify = "0.4"
sd-listen-fds = { version = "0.2", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
raunch = { version = "1", optional = true }

[features]
cli = ["daemon-slayer-core/cli", "async-trait"]
socket-activation = [
    "sd-listen-fds",
    "raunch",
    "daemon-slayer-core/socket-activation",
    "tipsy",
]
