[package]
edition = "2024"
name = "daemon-slayer-server"
version = "0.1.0"

[dependencies]
daemon-slayer-core = { workspace = true, features = ["server", "signal"] }
daemon-slayer-macros = { workspace = true, features = ["server"] }
futures = { workspace = true }
tap = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tipsy = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }

[target.'cfg(windows)'.dependencies]
registry = { workspace = true }
signal-hook = { workspace = true, optional = true }
tokio = { workspace = true, features = [
  "rt-multi-thread",
  "signal",
  "net",
  "macros",
  "sync",
] }
windows-service = { git = "https://github.com/aschey/windows-service-rs", rev = "32919aebe4c59f7855a8ebd72fe7d716db6a8f28" }


[target.'cfg(unix)'.dependencies]
tokio = { workspace = true, features = [
  "rt-multi-thread",
  "net",
  "io-util",
  "sync",
  "macros",
] }

[target.'cfg(target_os="linux")'.dependencies]
sd-notify = { workspace = true }
sd-listen-fds = { workspace = true, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
raunch = { workspace = true, optional = true }

[features]
cli = ["daemon-slayer-core/cli", "async-trait"]
socket-activation = [
  "sd-listen-fds",
  "raunch",
  "daemon-slayer-core/socket-activation",
  "tipsy",
]
