[package]
edition = "2021"
name = "daemon-slayer-client"
version = "0.1.0"

[dependencies]
eyre = "0.6.8"

[target.'cfg(windows)'.dependencies]
regex = "1.6.0"
windows-service = {git = "https://github.com/aschey/windows-service-rs", rev = "467408c9aba7d8221e5cf5a9992765ad7abeeb55"}

[target.'cfg(target_os="linux")'.dependencies]
systemd_client = {git = "https://github.com/aschey/systemd-client", rev = "5402ac4722cd6c0cf3c0f277c382ba20a1f5b3e6"}

[target.'cfg(target_os = "macos")'.dependencies]
launchd = "0.2.0"
