[package]
edition = "2021"
name = "daemon-slayer-client"
version = "0.1.0"

[dependencies]
async-trait = "0.1.57"
eyre = "0.6.8"
maybe-async-cfg = "0.2.3"
parity-tokio-ipc = {version = "0.9.0", optional = true}
reqwest = {version = "0.11.11", optional = true}
tokio = {version = "1.20.1", features = ["net"]}

[target.'cfg(windows)'.dependencies]
regex = "1.6.0"
windows-service = {git = "https://github.com/aschey/windows-service-rs", rev = "467408c9aba7d8221e5cf5a9992765ad7abeeb55"}

[target.'cfg(target_os="linux")'.dependencies]
systemd_client = {git = "https://github.com/aschey/systemd-client", rev = "530b606d9ed41049e4efb0a0ae85e1237e4f0784"}

[target.'cfg(target_os = "macos")'.dependencies]
directories = "4.0.1"
launchd = "0.2.0"
regex = "1.6.0"

[features]
async-tokio = []
blocking = ["reqwest/blocking"]
http-health-check = ["reqwest"]
ipc-health-check = ["parity-tokio-ipc", "async-tokio"]
