[package]
edition = "2024"
name = "grpc-tonic"
version = "0.1.0"

[workspace]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daemon-slayer = {path = "../../../crates/daemon-slayer", features = ["server-base", "client-base", "grpc-health-check", "extras"]}
prost = "0.11.0"
tokio = {version = "1.21.0", features = ["macros", "rt-multi-thread", "sync"]}
tonic = "0.8.1"
tonic-health = "0.7.1"
tracing = "0.1.36"

[build-dependencies]
tonic-build = "0.8.0"
