[package]
edition = "2024"
name = "minimal-separate"
version = "0.1.0"

[dependencies]
clap = { workspace = true, features = ["derive"] }
daemon-slayer = { path = "../../crates/daemon-slayer", features = [
  "client",
  "server",
  "signals",
] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[[bin]]
name = "minimal-client"
path = "src/bin/client.rs"

[[bin]]
name = "minimal-server"
path = "src/bin/server.rs"
