[package]
edition = "2021"
name = "daemon-slayer-core"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
tokio = {version = "1", features = ["sync"]}
