[package]
edition = "2021"
name = "daemon-slayer-core"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
clap = {version = "4", optional = true}
tokio = {version = "1", features = ["sync"]}

[features]
cli = ["clap"]
health-check = []
server = []
