[package]
edition = "2021"
name = "daemon-slayer-core"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
bus = {version = "2", optional = true}
clap = "4.0.17"
tokio = {version = "1", features = ["sync"]}
