[package]
edition = "2024"
name = "daemon-slayer"
version = "0.1.0"

[features]
client-standard = [
  "console",
  "client",
  "cli",
  "daemon-slayer-logging/system",
  "config",
  "error-handler",
  "process",
]
extras = [
  "file-watcher",
  #"task-queue"
]
server-standard = [
  "server",
  "cli",
  "daemon-slayer-logging/system",
  "logging",
  "config",
  "error-handler",
  "signals",
]
build-info = ["daemon-slayer-build-info"]
cli = [
  "daemon-slayer-cli",
  "daemon-slayer-logging?/cli",
  "daemon-slayer-server?/cli",
  "daemon-slayer-client?/cli",
  "daemon-slayer-console?/cli",
  "daemon-slayer-health-check?/cli",
  "daemon-slayer-error-handler?/cli",
  "daemon-slayer-config?/cli",
  "daemon-slayer-process?/cli",
  "daemon-slayer-notify?/cli",
]
client = ["daemon-slayer-client"]
docker = ["daemon-slayer-client?/docker"]
config = [
  "daemon-slayer-config",
  "daemon-slayer-client?/config",
  "daemon-slayer-console?/config",
  "daemon-slayer-logging?/config",
]
config-pretty-print = ["daemon-slayer-config/pretty-print"]
console = ["daemon-slayer-console"]
error-handler = ["daemon-slayer-error-handler"]
file-watcher = ["daemon-slayer-file-watcher"]
grpc-health-check = [
  "health-check",
  "daemon-slayer-health-check/grpc-health-check",
]
health-check = ["daemon-slayer-health-check"]
http-health-check = [
  "health-check",
  "daemon-slayer-health-check/http-health-check",
]
logging = ["daemon-slayer-logging"]
logging-ipc = ["daemon-slayer-logging/ipc"]
logging-linux-journald = ["daemon-slayer-logging/linux-journald"]
logging-mac-oslog = ["daemon-slayer-logging/mac-oslog"]
logging-system = ["daemon-slayer-logging/system"]
logging-windows-eventlog = ["daemon-slayer-logging/windows-eventlog"]
logging-file = ["daemon-slayer-logging/file"]
process = ["daemon-slayer-process"]
server = [
  "daemon-slayer-server",
  "daemon-slayer-config?/server",
  "daemon-slayer-logging?/server",
]
socket-activation = [
  "daemon-slayer-server?/socket-activation",
  "daemon-slayer-client?/socket-activation",
]
signals = ["daemon-slayer-signals"]
# task-queue = ["daemon-slayer-task-queue"]
tray = ["daemon-slayer-tray", "client"]
notify = ["daemon-slayer-notify", "daemon-slayer-error-handler?/notify"]
native-notification = ["notify", "daemon-slayer-notify/native-notification"]
dialog = ["notify", "daemon-slayer-notify/dialog"]
# network = ["daemon-slayer-network"]

[dependencies]
daemon-slayer-cli = { workspace = true, optional = true }
daemon-slayer-client = { workspace = true, optional = true }
daemon-slayer-config = { workspace = true, optional = true }
daemon-slayer-console = { workspace = true, optional = true }
daemon-slayer-core = { workspace = true }
daemon-slayer-error-handler = { workspace = true, optional = true }
daemon-slayer-file-watcher = { workspace = true, optional = true }
daemon-slayer-health-check = { workspace = true, optional = true }
daemon-slayer-logging = { workspace = true, optional = true }
daemon-slayer-process = { workspace = true, optional = true }
daemon-slayer-server = { workspace = true, optional = true }
daemon-slayer-signals = { workspace = true, optional = true }
# daemon-slayer-task-queue = { workspace = true, optional = true }
daemon-slayer-tray = { workspace = true, optional = true }
daemon-slayer-notify = { workspace = true, optional = true }
daemon-slayer-build-info = { workspace = true, optional = true }
# daemon-slayer-network = { workspace = true, optional = true }
