[package]
edition = "2021"
name = "daemon-slayer-client"
version = "0.1.0"

[dependencies]
arc-swap = {version = "1.5.1"}
async-trait = "0.1"
confique = {version = ">= 0.2.2", optional = true}
daemon-slayer-core = {path = "../daemon-slayer-core", features = ["config"]}
dyn-clonable = "0.9.0"
enumflags2 = "0.7.5"
eyre = "0.6"
serde = {version = "1"}

[target.'cfg(windows)'.dependencies]
regex = "1"
registry = "1.2"
utfx = "0.1"
windows-service = {git = "https://github.com/aschey/windows-service-rs", rev = "32919aebe4c59f7855a8ebd72fe7d716db6a8f28"}

[target.'cfg(target_os="linux")'.dependencies]
systemd_client = {git = "https://github.com/aschey/systemd-client", rev = "5d1c70d051a878933dc8d149393e768ca84fe0d8"}

[target.'cfg(target_os = "macos")'.dependencies]
directories = "4"
launchd = {git = "https://github.com/aschey/launchd", rev = "c4d6ae24de02cfc04097b1de3b33434eeb4a5d5e"}
once_cell = "1"
regex = "1.6"

[features]
cli = ["daemon-slayer-core/cli"]
config = ["confique"]
