[package]
name = "daemon-slayer-build-info"
version = "0.1.0"
edition = "2024"

[dependencies]
console = { workspace = true }
daemon-slayer-core = { workspace = true, features = ["cli"] }
vergen-pretty = { workspace = true, features = ["color"] }
async-trait = { workspace = true }
