[package]
edition = "2021"
name = "daemon-slayer-health-check"
version = "0.1.0"

[dependencies]
daemon-slayer-core = { path = "../daemon-slayer-core", features = [
    "health-check",
] }
parity-tokio-ipc = { git = "https://github.com/aschey/parity-tokio-ipc", rev = "588198a0abb32a79f6f3e656ff0472008e4ba9b8", optional = true }
reqwest = { version = "0.11", optional = true }
tokio = { version = "1", features = ["net"] }
tonic = { version = "0.9", optional = true }
tonic-health = { version = "0.9", optional = true }

[features]
cli = ["daemon-slayer-core/cli"]
grpc-health-check = ["tonic", "tonic-health"]
http-health-check = ["reqwest"]
ipc-health-check = ["parity-tokio-ipc"]
